"""migracija

Revision ID: 80cdd2a14b55
Revises: 
Create Date: 2025-12-15 15:05:44.087143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80cdd2a14b55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id_location', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_location', sa.String(length=140), nullable=False),
    sa.Column('address_location', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('plays',
    sa.Column('id_play', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_play', sa.String(length=140), nullable=False),
    sa.Column('genre_play', sa.String(length=140), nullable=False),
    sa.Column('duration_play', sa.Time(), nullable=False),
    sa.Column('description_play', sa.String(length=1000), nullable=False),
    sa.Column('category_play', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_play')
    )
    op.create_table('halls',
    sa.Column('id_hall', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('capacity_hall', sa.Integer(), nullable=False),
    sa.Column('category_hall', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_location'], ['locations.id_location'], ),
    sa.PrimaryKeyConstraint('id_hall')
    )
    op.create_table('performances',
    sa.Column('id_performance', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_play', sa.Integer(), nullable=False),
    sa.Column('id_hall', sa.Integer(), nullable=False),
    sa.Column('date_performance', sa.DateTime(), nullable=False),
    sa.Column('price_performance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_hall'], ['halls.id_hall'], ),
    sa.ForeignKeyConstraint(['id_play'], ['plays.id_play'], ),
    sa.PrimaryKeyConstraint('id_performance')
    )
    op.create_table('seats',
    sa.Column('id_seat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_hall', sa.Integer(), nullable=False),
    sa.Column('row_seat', sa.Integer(), nullable=False),
    sa.Column('column_seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hall'], ['halls.id_hall'], ),
    sa.PrimaryKeyConstraint('id_seat')
    )
    op.create_table('reservations',
    sa.Column('id_reservation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_performance', sa.Integer(), nullable=False),
    sa.Column('id_seat', sa.Integer(), nullable=False),
    sa.Column('date_reservation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_performance'], ['performances.id_performance'], ),
    sa.ForeignKeyConstraint(['id_seat'], ['seats.id_seat'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_reservation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    op.drop_table('seats')
    op.drop_table('performances')
    op.drop_table('halls')
    op.drop_table('plays')
    op.drop_table('locations')
    # ### end Alembic commands ###
